POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs time)
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="╰─▶ "
POWERLEVEL9K_PROMPT_ON_NEWLINE=true

POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="blue"
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND="red"
POWERLEVEL9K_CONTEXT_SUDO_FOREGROUND="red"
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND="red"
POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND="green"

POWERLEVEL9K_CONTEXT_TEMPLATE="%M"
